[phases.setup]
nixPkgs = ['python3Full', 'postgresql']

[phases.install]
cmds = [
    'python3 -m ensurepip --upgrade',
    'python3 -m pip install --upgrade pip',
    'python3 -m pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python3 -c "import sys; print(f\"Python version: {sys.version}\")"',
    'python3 -m pip list'
]

[start]
cmd = [
  "python3",
  "-c",
  "import os, uvicorn; port=int(os.getenv('PORT','8000')); uvicorn.run('src.backend.main:app', host='0.0.0.0', port=port)"
]
