[phases.setup]
nixPkgs = ['python3Full', 'postgresql']

[phases.install]
cmds = [
    'python3 -m ensurepip --upgrade',
    'python3 -m pip install --upgrade pip',
    'python3 -m pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python3 -c "import sys; print(f\"Python version: {sys.version}\")"',
    'python3 -m pip list'
]

[start]
# Use shell so $PORT is expanded by the runtime
cmd = ["sh", "-c", "python3 -m uvicorn src.backend.main:app --host 0.0.0.0 --port ${PORT:-8000}"]
