@echo off
echo Starting SmartLinks Backend with RCP Support...
cd /d "c:\smartlinks-autopilot"
echo Activating virtual environment...
call .venv\Scripts\activate.bat
echo Starting server on http://127.0.0.1:8000...
python start_server_direct.py
